# Generated by Django 4.1.7 on 2023-03-22 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField(max_length=200)),
                ('artist_age', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=150, unique=True)),
                ('year_of_entrance', models.IntegerField()),
                ('country_capital', models.CharField(max_length=150, unique=True)),
                ('country_hymn', models.CharField(max_length=150)),
                ('quality_factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_year', models.IntegerField()),
                ('final_date', models.DateField()),
                ('motto', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='HostCity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host_city_name', models.CharField(max_length=150, unique=True)),
                ('host_city_population', models.IntegerField()),
                ('host_city_mayor', models.CharField(max_length=150)),
                ('is_capital', models.BooleanField()),
                ('quality_factor', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=150)),
                ('venue_adress', models.CharField(max_length=200, unique=True)),
                ('capacity', models.IntegerField()),
                ('rating', models.FloatField()),
                ('host_city_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='eurovision.hostcity')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField(max_length=200)),
                ('release_date', models.CharField(default='', max_length=200)),
                ('album_name', models.CharField(default='', max_length=150)),
                ('artist_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='eurovision.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Ids',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.IntegerField()),
                ('points', models.IntegerField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eurovision.artist')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eurovision.country')),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eurovision.edition')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='artists',
            field=models.ManyToManyField(through='eurovision.Ids', to='eurovision.artist'),
        ),
        migrations.AddField(
            model_name='edition',
            name='countries',
            field=models.ManyToManyField(through='eurovision.Ids', to='eurovision.country'),
        ),
        migrations.AddField(
            model_name='edition',
            name='venue_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='eurovision.venue'),
        ),
        migrations.AddField(
            model_name='country',
            name='artists',
            field=models.ManyToManyField(through='eurovision.Ids', to='eurovision.artist'),
        ),
        migrations.AddField(
            model_name='country',
            name='editions',
            field=models.ManyToManyField(through='eurovision.Ids', to='eurovision.edition'),
        ),
        migrations.AddField(
            model_name='artist',
            name='countries',
            field=models.ManyToManyField(through='eurovision.Ids', to='eurovision.country'),
        ),
        migrations.AddField(
            model_name='artist',
            name='editions',
            field=models.ManyToManyField(through='eurovision.Ids', to='eurovision.edition'),
        ),
    ]
