# Generated by Django 4.1.7 on 2023-03-22 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eurovision', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='place',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ids',
            name='points',
            field=models.IntegerField(default=0),
        ),
    ]
