# Generated by Django 4.1.7 on 2023-03-22 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eurovision', '0002_alter_ids_place_alter_ids_points'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='artist',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='eurovision.artist'),
        ),
    ]
