# Generated by Django 4.1.7 on 2023-03-22 08:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eurovision', '0003_alter_ids_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='country',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='eurovision.country'),
        ),
        migrations.AlterField(
            model_name='ids',
            name='edition',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, to='eurovision.edition'),
        ),
    ]
