# Generated by Django 4.1.7 on 2023-03-22 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eurovision', '0004_alter_ids_country_alter_ids_edition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ids',
            name='artist',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='eurovision.artist'),
        ),
        migrations.AlterField(
            model_name='ids',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eurovision.country'),
        ),
        migrations.AlterField(
            model_name='ids',
            name='edition',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eurovision.edition'),
        ),
    ]
