# Generated by Django 4.1.7 on 2023-03-22 10:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eurovision', '0005_alter_ids_artist_alter_ids_country_alter_ids_edition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='editions',
        ),
        migrations.RemoveField(
            model_name='country',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='edition',
            name='artists',
        ),
        migrations.RemoveField(
            model_name='ids',
            name='artist',
        ),
        migrations.AddField(
            model_name='artist',
            name='country',
            field=models.ForeignKey(null='True', on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='eurovision.country'),
            preserve_default='True',
        ),
        migrations.AlterField(
            model_name='ids',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eurovision.country'),
        ),
        migrations.AlterField(
            model_name='ids',
            name='edition',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eurovision.edition'),
        ),
    ]
