# Generated by Django 4.1.7 on 2023-03-22 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eurovision', '0006_remove_artist_countries_remove_artist_editions_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='eurovision.country'),
        ),
    ]
