# Generated by Django 4.1.7 on 2023-03-22 11:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eurovision', '0007_alter_artist_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='eurovision.country'),
        ),
    ]
